chore: remove jquery dep
* removing "jquery" dep fix CVE issues:
  - https://nvd.nist.gov/vuln/detail/CVE-2015-9251 should not be so serious anymore.
	- Future updates regarding https://nvd.nist.gov/vuln/detail/CVE-2016-10707 might be needed.

* fix gulp-sourcemaps version to 1.6.0, updating was causing error:
  ```
  Error: Cannot find module 'debug'
  ```

* add package-lock.json file introduced by new versions of `npm`